select top 10 * from [dbo].[olist_customers_dataset]
select top 10 * from [dbo].[olist_geolocation_dataset]
select top 10 * from [dbo].[olist_order_items_dataset]
select top 10 * from [dbo].[olist_order_payments_dataset]
select top 10 * from [dbo].[olist_orders_dataset]
select top 10 * from [dbo].[olist_products_dataset]
select top 10 * from [dbo].[olist_sellers_dataset]
select top 10 * from [dbo].[product_category_name_translation]
